name: Fleet Deployment Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  local-deploy:
    # Tells GitHub to bypass cloud runners and hit your ThinkPad directly
    runs-on: self-hosted

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Test Native Local Pipeline Execution
        run: |
          Write-Output "Pipeline executing natively on my ThinkPad!"
          Write-Output "Checking active Docker containers..."
          docker ps
